server:
  port: 8887
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
    username: root
    password: root
github:
  Client:
    id: Iv1.2533d223159ef22a
    secret: dcdfdd8e3f3c30c055ee7a0b13522b1658ff6152
  Redirect:
    uri: http://localhost:8887/callback

mybatis:
  configuration:
    map-underscore-to-camel-case: true
