server:
  port: 80

#数据源 mvc配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.13.75:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**

#Github第三方
github:
  Client:
    id: Iv1.2533d223159ef22a
    secret: 194159fe1026e053e137dd63717aca322baa6f6f
  Redirect:
    uri: http://47.115.13.75/callback

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zyshuang.community.mapper
  mapper-locations: classpath:mapper/*.xml

#云存储
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4Fza6F6nH49MjNggdwBd
  accessKeySecret:  JAlOuSAhPlHvS9S9zxjhGdxxDJkRyR
  bucketName: zyshuang
  filePath: images/
  expiration: 315360000

#日志
logging:
  level:
    root: info
  file:
    name: logs/community.log
    max-size: 100MB
    max-history: 30
