server:
  port: 8887

#数据源 mvc配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
    username: root
    password: root
  mvc:
    static-path-pattern: /**

#Github第三方
github:
  Client:
    id: Iv1.2533d223159ef22a
    secret: dcdfdd8e3f3c30c055ee7a0b13522b1658ff6152
  Redirect:
    uri: http://localhost:8887/callback

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zyshuang.community.mapper
  mapper-locations: classpath:mapper/*.xml

#云存储
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4Fza6F6nH49MjNggdwBd
  accessKeySecret:  JAlOuSAhPlHvS9S9zxjhGdxxDJkRyR
  bucketName: zyshuang
  filePath: images/
  expiration: 315360000

#日志
logging:
  level:
    root: info
    com:
      zyshuang:
        community:
          mapper: debug
  file:
    name: logs/community.log
    max-size: 100MB
    max-history: 15
